### ISSUE TITLE
More removal functionality for DsChain implementations

### ISSUE THREAD

**Issue by JulianDicken** [Hyomoto/FASTv33#1]
remove_index removes chain at index
remove_value removes all matching values
remove_type removes all values of matching type

**Comment by Hyomoto** [comment]
The issue here is that DsChain doesn't actually have any add or remove functionality.  Originally it had some support for adding links, but the problem was that anything that inherits this base type then inadvertently absorbs it.  So, for example, how does remove_type function in context of a stack?  There's probably a way forwards on this, but I think you probably want this added to DsLinkedList.
